### ISSUE TITLE
What is the path to soap element

### ISSUE THREAD

**Issue by minyixie** [yaronn/ws.js#10]
In the following sample, I am confused what is the path to the soap elements

//add attachment to the soap request
 ws.addAttachment(ctx, "request", "//*[local-name(.)='File1']", 
                    "me.jpg", "image/jpeg")

what is the "//*[local-name(.)='File1']", how can I use it or replace it by what?

**Comment by yaronn** [comment]
Hi

The File1 refers to the File1 element in the SOAP message that appears before:

   var request = '<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope">' +
                    '<s:Body>' +
                      '<EchoFiles xmlns="http://tempuri.org/">' +                        
                          '<File1 />' +
                      '</EchoFiles>' +
                    '</s:Body>' +
                  '</s:Envelope>

If you have a sample SOAP request you want to send then check which element should contain the attachment and use it in the xpath.

**Comment by minyixie** [comment]
Thanks Yaronn for the reply but I am still not quite clear on how to write the xpath. 

Using my xml and soap message for example:

the part I was going to call in the xml is

<xs:element name="get_image_png">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="access_key" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="name" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="image_name" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="get_image_pngResponse">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="get_image_pngResult" nillable="true" type="xs:base64Binary"/>
</xs:sequence>
</xs:complexType>
</xs:element>
