### ISSUE TITLE
What is the path to soap element (sorry for unexpected close)

### ISSUE THREAD

**Issue by minyixie** [yaronn/ws.js#11]
The original question is

"In the following sample, I am confused what is the path to the soap elements

//add attachment to the soap request
ws.addAttachment(ctx, "request", "//*[local-name(.)='File1']", 
"me.jpg", "image/jpeg")

what is the "//*[local-name(.)='File1']", how can I use it or replace it by what?"

and the reply from yaronn is

"Hi

The File1 refers to the File1 element in the SOAP message that appears before:

              var request = '<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope">' +
                '<s:Body>' +
                  '<EchoFiles xmlns="http://tempuri.org/">' +                        
                      '<File1 />' +
                  '</EchoFiles>' +
                '</s:Body>' +
              '</s:Envelope>
If you have a sample SOAP request you want to send then check which element should contain the attachment and use it in the xpath."

**Comment by minyixie** [comment]
Thanks Yaronn for the reply but I am still not clear. Let me use my case for example

the xml content is

the request:
<xs:element name="get_image_png">
    <xs:complexType>
       <xs:sequence>
           <xs:element minOccurs="0" name="access_key" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="name" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="image_name" nillable="true" type="xs:string"/>
       </xs:sequence>
    </xs:complexType>
</xs:element>

the response
<xs:element name="get_image_pngResponse">
   <xs:complexType>
     <xs:sequence>
        <xs:element minOccurs="0" name="get_image_pngResult" nillable="true" type="xs:base64Binary"/>
     </xs:sequence>
   </xs:complexType>
</xs:element>

What I want is to get the binary data from get_image_pngResult.

So far, I have two issues. 

1) the <File1> you mentioned is in the request, which is the get_image_png in my case. so why and how can i get the xpath to the response get_image_pngResult?
2) the xpath used in your example is '//*[local-name]="File1"'. so how to convert the request to this path? to my case, I have no idea. I did some search, it said the path can be represent as 'get_image_pngResponce{}/get_image_pngResults'. but it does not work for me. 

Could you give me any hints on that? thanks for your help. 

Regards

**Comment by yaronn** [comment]
Hi

In your case the xpath could be:

    //*[local-name(.)='get_image_pngResult']

note that it is not clear from your message if your server uses base64 attachment or mtom. in the former case you do not need to add/get attachment methods in ws.js. just get the base64 as string (using the xpath) and convert it to binary:

    var buf = new Buffer(b64string, 'base64');

**Comment by minyixie** [comment]
Thanks so much for help and I will try and see what happens.

**Comment by minyixie** [comment]
Hi Yaronn, 

I tried the two ways as you suggested but unlucky, I could not get the data. 

1) By using the xpath to get he base64 data directly without add/get attachment, I only receive the content ID, which is
     {get_image_png{Include{attributes{href:"cid:http://some_address"}}}}
and the content of data is cut off, which means the binary data can not be seen in ctx. 

2) I use the //*[local-name(.)='get_image_pngResult'] way, but I got error
    /Users/apple/node_modules/ws.js/lib/utils.js:70
  elem.appendChild(t)	
       ^
TypeError: Cannot call method 'appendChild' of undefined
    at Object.setElementValue (/Users/apple/node_modules/ws.js/lib/utils.js:70:8)
    at Object.addAttachment (/Users/apple/node_modules/ws.js/lib/ws.js:53:9)
    at Object.<anonymous> (/Users/apple/Desktop/AerFaceLab/task3_4/test.js:179:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

3) I tried another way without using Mtom
var handlers =  [new Http()];

ws.send(handlers, ctx, function(ctx) {      
	console.log(ctx); 
})

in the ctx, there is the octet stream of the image (I think it is image because the first line contains PNG text). But the problem is I could not use the octet stream to represent the image. I tried to use Buffer to convert the stream to binary, utf8, utf16, base64, but none of them works. I also tried to save the octet stream as binary file, then retrieve it as base64 data in node.js, but it does not work neither. 

I am new to soap message use, so I might miss something, please help on this. Thanks.

**Comment by yaronn** [comment]
can you publish the full response message? (you can get it from the service
documentaion, a working client or a network sniffer). I wan to udnerstand
which attachment standard it uses.

On Thu, Mar 26, 2015 at 2:36 AM, minyixie <notifications@github.com> wrote:

> Hi Yaronn,
>
> I tried the two ways as you suggested but unlucky, I could not get the
> data.
>
> 1) By using the xpath to get he base64 data directly without add/get
> attachment, I only receive the content ID, which is
> {get_image_png{Include{attributes{href:"cid:http://some_address"}}}}
> and the content of data is cut off, which means the binary data can not be
> seen in ctx.
>
> 2) I use the //*[local-name(.)='get_image_pngResult'] way, but I got error
> /Users/apple/node_modules/ws.js/lib/utils.js:70
> elem.appendChild(t)
>
> ^
> TypeError: Cannot call method 'appendChild' of undefined
> at Object.setElementValue
> (/Users/apple/node_modules/ws.js/lib/utils.js:70:8)
> at Object.addAttachment (/Users/apple/node_modules/ws.js/lib/ws.js:53:9)
> at Object. (/Users/apple/Desktop/AerFaceLab/task3_4/test.js:179:4)
> at Module._compile (module.js:456:26)
> at Object.Module._extensions..js (module.js:474:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:312:12)
> at Function.Module.runMain (module.js:497:10)
> at startup (node.js:119:16)
> at node.js:906:3
>
> 3) I tried another way without using Mtom
> var handlers = [new Http()];
>
> ws.send(handlers, ctx, function(ctx) {
>
> console.log(ctx);
> })
>
> in the ctx, there is the octet stream of the image (I think it is image
> because the first line contains PNG text). But the problem is I could not
> use the octet stream to represent the image. I tried to use Buffer to
> convert the stream to binary, utf8, utf16, base64, but none of them works.
> I also tried to save the octet stream as binary file, then retrieve it as
> base64 data in node.js, but it does not work neither.
>
> I am new to soap message use, so I might miss something, please help on
> this. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/ws.js/issues/11#issuecomment-86265936>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by minyixie** [comment]
Thanks for the quick reply. The full content of ctx is below:

{ webserver_port: 8001 }
{ request: '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/"><soapenv:Header/><soapenv:Body><tem:get_image_png><tem:access_key>Z6N41239</tem:access_key><tem:name>girl</tem:name><tem:image_name>girl1</tem:image_name></tem:get_image_png></soapenv:Body></soapenv:Envelope>',
  url: 'https://www.aercloud.net/webapi?wsdl',
  action: 'http://tempuri.org/IISMWebAPI/get_image_png',
  contentType: 'text/xml; chartset=utf16',
  contentEncoding: 'text/xml',
  response: '\r\n--uuid:b582909b-0d45-4983-9480-eb89010588b4+id=10899\r\nContent-ID: <http://tempuri.org/0>\r\nContent-Transfer-Encoding: 8bit\r\nContent-Type: application/xop+xml;charset=utf-8;type="text/xml"\r\n\r\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><get_image_pngResponse xmlns="http://tempuri.org/"><get_image_pngResult><xop:Include href="cid:http://tempuri.org/1/635629279886408732" xmlns:xop="http://www.w3.org/2004/08/xop/include"/></get_image_pngResult></get_image_pngResponse></s:Body></s:Envelope>\r\n--uuid:b582909b-0d45-4983-9480-eb89010588b4+id=10899\r\nContent-ID: <http://tempuri.org/1/635629279886408732>\r\nContent-Transfer-Encoding: binary\r\nContent-Type: application/octet-stream\r\n\r\n�PNG\r\n\u001a\n\u0000\u0000\u0000\rIHDR\u0000\u0000\u0000M\u0000\u0000\u0000M\b\u0002\u0000\u0000\u0000lk~�\u0000\u0000\u0000\u0001sRGB\u0000��\u001c�\u0000\u0000\u0000\u0004gAMA\u0000\u0000��\u000b�a\u0005\u0000\u0000\u0000\tpHYs\u0000\u0000\u000e�\u0000\u0000\u000e�\u0001�o�d\u0000\u0000$UIDATx^M�۳#�u���V�r��\n��\u0001c�1f((0v��*�UI�ʩ<9ϩ�{���6\u0017g\u0018f�9R�[���5�F��Z�{��o��Z�5����w\u000bc�|_����O���Ty��S���U�]���j]Ve������s�(x�e�\u0017g��V�8Y���i��z�q��e^��<�s���(X��2F�X,�q��`β������9]1O�4�\u001d���p\\���8�Ӵ��yΙ�(\u0017\u0004��a���<���m�i�~\u000e��䒮�|��\u0018G��ɢP�\u001f��G\u000f���-\u0018�(2\u0014�\u0019�\n�j>�V(\u0017\'V�����̼�y�\u001ec�]��o\u001ekzT�>f�1VT�q�����a\u0018А�\u0004�Y��Q\u0004\u0014\u0018�{��8M#zk�2?c��\u0015�\f\u0015���\'\u00197aQ��\u0019�ċ����\bʲ�>ȫ"/������t\\�+��-3�ΩUY�\u0004��j�1\'-�9�[0\u001e��Ι\u001eAPf\u000eQ8�8\\�\u001b��g\\8�Ȅ�|X�\u0011�/�� �1��m̝�����3\u0003!X��\\���p^ʧo?�(fӆ�4co��\b�\f\'T�\u0019_ᦆ?U�Y�(��+g\fqΗ�{�\u000b�@J\u001d���Z���US���\b^U\tŰ��"�\u0017*=�P�\u0019�\u0012#^�� H}\u0011z)���x��l��pM\f�\f��b�\t�Yk\u000e\u0013\b��i\u0018y�\u001e6�rW\rY�����\u0001����y�\b���;��$wUX\u0004lx���[^\u0005���R3/T�\u0000��\n,ȍ\u000b��‏D�\u0001�-~Ĕ�\u0003ph�tq���\u0010Q��x\u000eg�Q�e\u0001�\u001c�&�FS}7\u000f"�\bg�
...
u0000�?�\u0006�p��\\m���RU@\\��8\u0017㑳�j��\u001fș��j����\u0019�Ƹ��:����O�x\u0010�BCp*�T\u001c.Ć��X�X�k.gz��W\u0005���4�f܋̺\u0012x���\u000fd\u0002�R�T�\u0000\u0000\u0000\u0000\u0000IEND�B`�\r\n--uuid:b582909b-0d45-4983-9480-eb89010588b4+id=10899--\r\n',
  resp_contentType: 'multipart/related; type="application/xop+xml";start="<http://tempuri.org/0>";boundary="uuid:b582909b-0d45-4983-9480-eb89010588b4+id=10899";start-info="text/xml"',
  statusCode: 200 }

I hope they are what you want. 

Regards
Minyi

**Comment by yaronn** [comment]
what do you get if you try as in the mtom sample:

    ...
    var file = ws.getAttachment(ctx, "response", "//*[local-name(.)='get_image_pngResult']")
    fs.writeFileSync("result.jpg", file)

**Comment by minyixie** [comment]
Without 
ws.addAttachment(ctx, "request","//*[local-name(.)='get_image_pngResult']","me.png",'image/png');

I got the response as:

...(same as previous)
u0006�\n\u0003<��P�\u0019\u001a�<���p�B��>���7��^6�M�I�\u0004j�@h��4\tʊ3)D\u001cL\u0015#\u001d\u0005�\u001c\\��|��;��\nS�Kv+\u0018\u0006^�\u0015^��\u0010\u0014�Ӆ�`m\u000f�a\u0010\u0004@Gh�\u0007\u0002����C\u0010\u0000%[0U�\u0018^\t\u0000�D\u0000�?�\u0006�p��\\m���RU@\\��8\u0017㑳�j��\u001fș��j����\u0019�Ƹ��:����O�x\u0010�BCp*�T\u001c.Ć��X�X�k.gz��W\u0005���4�f܋̺\u0012x���\u000fd\u0002�R�T�\u0000\u0000\u0000\u0000\u0000IEND�B`�\r\n--uuid:b582909b-0d45-4983-9480-eb89010588b4+id=10903--\r\n',
  resp_contentType: 'multipart/related; type="application/xop+xml";start="<http://tempuri.org/0>";boundary="uuid:b582909b-0d45-4983-9480-eb89010588b4+id=10903";start-info="text/xml"',
  statusCode: 200 }
end tag name: $M������j}��#�=�W���/^�n{�&P)q��?����}@n~����qwC
                                                               �5JT���-滏A�%�`�]� is not match the current start tagName:�K7N$T
source code out of document root

TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at Object.getAttachment (/Users/apple/node_modules/ws.js/lib/ws.js:64:10)
    at pth (/Users/apple/Desktop/AerFaceLab/task3_4/test.js:186:21)
    at /Users/apple/node_modules/ws.js/lib/ws.js:27:5
    at Request._callback (/Users/apple/node_modules/ws.js/lib/handlers/client/http.js:25:7)
    at Request.self.callback (/Users/apple/node_modules/ws.js/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/apple/node_modules/ws.js/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/apple/node_modules/ws.js/node_modules/request/request.js:1187:12)

with the 
ws.addAttachment(ctx, "request","//*[local-name(.)='get_image_pngResult']","me.png",'image/png');

the response is with error:

{ webserver_port: 8001 }

/Users/apple/node_modules/ws.js/lib/utils.js:70
  elem.appendChild(t)	
       ^
TypeError: Cannot call method 'appendChild' of undefined
    at Object.setElementValue (/Users/apple/node_modules/ws.js/lib/utils.js:70:8)
    at Object.addAttachment (/Users/apple/node_modules/ws.js/lib/ws.js:53:9)
    at Object.<anonymous> (/Users/apple/Desktop/AerFaceLab/task3_4/test.js:179:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by yaronn** [comment]
do you try to add an attachment (generate request) or get an attachment
(extract from response)? you used addAttachment but note I have suggested
getAttachment (and also second parameter should be "response").

On Thu, Mar 26, 2015 at 3:34 AM, minyixie <notifications@github.com> wrote:

> Without
> ws.addAttachment(ctx,
> "request","//*[local-name(.)='get_image_pngResult']","me.png",'image/png');
>
> I got the response as:
>
> ...(same as previous)
> u0006�\n\u0003<��P�\u0019\u001a�<���p�B��>���7��^6�M�I�\u0004j�@h
> <https://github.com/h>
> ��4\tʊ3)D\u001cL\u0015#\u001d\u0005�\u001c\��|��;��\nS�Kv+\u0018\u0006^�\u0015^��\u0010\u0014�Ӆ�
> m\u000f�a\u0010\u0004@Gh
> �\u0007\u0002����C\u0010\u0000%[0U�\u0018^\t\u0000�D\u0000�?�\u0006�p��\\m���RU@
> \\��8\u0017㑳�j��\u001fș��j����\u0019�Ƹ��:����O�x\u0010�BCp*�T\u001c.Ć��X�X�k.gz��W\u0005���4�f܋̺\u0012x���\u000fd\u0002�R�T�\u0000\u0000\u0000\u0000\u0000IEND�B
> �\r\n--uuid:b582909b-0d45-4983-9480-eb89010588b4+id=10903--\r\n',
> resp_contentType: 'multipart/related; type="application/xop+xml";start="
> http://tempuri.org/0
> ";boundary="uuid:b582909b-0d45-4983-9480-eb89010588b4+id=10903";start-info="text/xml"',
> statusCode: 200 }
> end tag name: $M������j}��#�=�W���/^�n{�&P)q��?����}@n
> <https://github.com/n>~����qwC
> �5JT���-滏A�%�`�]� is not match the current start tagName:�K7N$T
> source code out of document root
>
> TypeError: First argument needs to be a number, array or string.
> at new Buffer (buffer.js:188:15)
> at Object.getAttachment (/Users/apple/node_modules/ws.js/lib/ws.js:64:10)
> at pth (/Users/apple/Desktop/AerFaceLab/task3_4/test.js:186:21)
> at /Users/apple/node_modules/ws.js/lib/ws.js:27:5
> at Request._callback
> (/Users/apple/node_modules/ws.js/lib/handlers/client/http.js:25:7)
> at Request.self.callback
> (/Users/apple/node_modules/ws.js/node_modules/request/request.js:344:22)
> at Request.emit (events.js:98:17)
> at Request.
> (/Users/apple/node_modules/ws.js/node_modules/request/request.js:1239:14)
> at Request.emit (events.js:117:20)
> at IncomingMessage.
> (/Users/apple/node_modules/ws.js/node_modules/request/request.js:1187:12)
>
> with the
> ws.addAttachment(ctx,
> "request","//*[local-name(.)='get_image_pngResult']","me.png",'image/png');
>
> the response is with error:
>
> { webserver_port: 8001 }
>
> /Users/apple/node_modules/ws.js/lib/utils.js:70
> elem.appendChild(t)
>
> ^
> TypeError: Cannot call method 'appendChild' of undefined
> at Object.setElementValue
> (/Users/apple/node_modules/ws.js/lib/utils.js:70:8)
> at Object.addAttachment (/Users/apple/node_modules/ws.js/lib/ws.js:53:9)
> at Object. (/Users/apple/Desktop/AerFaceLab/task3_4/test.js:179:4)
> at Module._compile (module.js:456:26)
> at Object.Module._extensions..js (module.js:474:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:312:12)
> at Function.Module.runMain (module.js:497:10)
> at startup (node.js:119:16)
> at node.js:906:3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/ws.js/issues/11#issuecomment-86287301>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by minyixie** [comment]
Yes, I did that.

What I mentioned is

1) ws.addAttachment(ctx,
>
"request","//*[local-name(.)='get_image_pngResult']","me.png",'image/png');

Var hanlder={new Http(), new Mtom()};

Ws.send(CTX, handler, function(er, CTX){
console.log(CTX);
});

2)
Var hanlder={new Http(), new Mtom()};

Ws.send(CTX, handler, function(er, CTX){
console.log(CTX);
});

Minyi

**Comment by yaronn** [comment]
do you use nodejs (ws.js) to build a client or a server or both?

you should also check the attachments test code:

https://github.com/yaronn/ws.js/blob/master/test/integration/client/mtom.js

it is a test ws.js client which sends and receives attachments from C# / WCF.

**Comment by minyixie** [comment]
The server is built by other staff. What I am doing is on client side to
use soap message to past my input to the server function and then recieve
the reponse.

This work by using java and c# has been done. Now, I need to use JavaScript
with nodejs to implement the same process.

**Comment by yaronn** [comment]
does your client sends an attachment, receives an attachment or both?

in case you only receive an attachment you only need ws.getAttachment, not
sure why your previous messages mentioned addAttachment. Can you publish
your full client code?

On Thu, Mar 26, 2015 at 4:19 AM, minyixie <notifications@github.com> wrote:

> The server is built by other staff. What I am doing is on client side to
> use soap message to past my input to the server function and then recieve
> the reponse.
>
> This work by using java and c# has been done. Now, I need to use JavaScript
> with nodejs to implement the same process.
> On 26/03/2015 1:13 PM, "Yaron Naveh" <notifications@github.com> wrote:
>
> > do you use nodejs (ws.js) to build a client or a server or both?
> >
> > you should also check the attachments test code:
> >
> >
> https://github.com/yaronn/ws.js/blob/master/test/integration/client/mtom.js
> >
> > it is a test ws.js client which sends and receives attachments from C# /
> > WCF.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/yaronn/ws.js/issues/11#issuecomment-86294329>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/ws.js/issues/11#issuecomment-86296852>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by minyixie** [comment]
There is no attachment in request and the attachment is only in the
response. The process is :
Name and image name parameters are in the request. The corresponding image
content in base64 is attached in response.

I will attach the code later. Thanks so much.

**Comment by minyixie** [comment]
var http = require("http");
var url = require("url");
var io = require("socket.io");
var fs = require('fs');
var path = require("path");

var ws = require('ws.js'),
	Http = ws.Http,
	Mtom = ws.Mtom;


var server = http.createServer(function(request, response){

	var pathh = url.parse(request.url).pathname;
	var extension = path.extname(pathh).toLowerCase();

	switch(extension){ 
		case '':
			fs.readFile(__dirname + pathh + "/default.html", function(error, data){
				if (error){
					response.writeHead(404);
					response.write("The requested page does not exist");
					response.end();
				} else{
					response.writeHead(200, {"Content-Type": "text/html"});
                    response.write(data);
                    response.end();
                }
			});
		break;
		case '.html':
			fs.readFile(__dirname + pathh, function(error, data){
				if (error){
					response.writeHead(404);
					response.write("The requested page does not exist");
					response.end();
				} else{
					response.writeHead(200, {"Content-Type": "text/html"});
                    response.write(data);
                    response.end();
                }
			});
		break; 
		case '.png':
			fs.readFile(__dirname + pathh, function(error, data){
				if (error){
					response.writeHead(404);
					response.write("The requested page does not exist");
					response.end();
				} else{
        			response.writeHead(200, {"Content-Type": "image/png"});
        			response.write(data);
                    response.end();
                }
    		});
    	break;
    	case '.jpg':
			fs.readFile(__dirname + pathh, function(error, data){
				if (error){
					response.writeHead(404);
					response.write("The requested page does not exist");
					response.end();
				} else{
        			response.writeHead(200, {"Content-Type": "image/jpeg"});
        			response.write(data);
                    response.end();
                }
    		});
    	break;
    	case '.jpeg':
			fs.readFile(__dirname + pathh, function(error, data){
				if (error){
					response.writeHead(404);
					response.write("The requested page does not exist");
					response.end();
				} else{
        			response.writeHead(200, {"Content-Type": "image/jpeg"});
        			response.write(data);
                    response.end();
                }
    		});
    	break;
    	case '.css':
			fs.readFile(__dirname + pathh, function(error, data){
				if (error){
					response.writeHead(404);
					response.write("The requested page does not exist");
					response.end();
				} else{
        			response.writeHead(200, {"Content-Type": "text/css"});
        			response.write(data);
                    response.end();
                }
    		});
    	break;
    	case '.js':
			fs.readFile(__dirname + pathh, function(error, data){
				if (error){
					response.writeHead(404);
					response.write("The requested page does not exist");
					response.end();
				} else{
        			response.writeHead(200, {"Content-Type": "text/javascript"});
        			response.write(data);
                    response.end();
                }
    		});
    	break;
      case '.csv':
      fs.readFile(__dirname + pathh, function(error, data){
        if (error){
          response.writeHead(404);
          response.write("The requested page does not exist");
          response.end();
        } else{
              response.writeHead(200, {"Content-Type": "text/javascript"});
              response.write(data);
                    response.end();
                }
        });
      break;
      case '.json':
      fs.readFile(__dirname + pathh, function(error, data){
        if (error){
          response.writeHead(404);
          response.write("The requested page does not exist");
          response.end();
        } else{
              response.writeHead(200, {"Content-Type": "text/javascript"});
              response.write(data);
                    response.end();
                }
        });
      break;
		default:
			response.writeHead(404);
			response.write("The requested page does not exist"); 
			response.end();
				
		break;
	}
});


var port_localhost = JSON.parse(fs.readFileSync('config/web_server.json','utf8'));
console.log(port_localhost);
server.listen(port_localhost.webserver_port);

var serv_io = io.listen(server);
var message = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">' +
	   '<soapenv:Header/>' + 
	   '<soapenv:Body>' + 
		  '<tem:get_image_png>' + 
			 '' + 
			 '<tem:access_key>UxKjqyuQUANqAC8eNVG6EOjs2FBHZ6N41239</tem:access_key>' + 
			 '' + 
			 '<tem:name>girl</tem:name>' + 
			 '' + 
			 '<tem:image_name>girl1</tem:image_name>' +
		  '</tem:get_image_png>' + 
	   '</soapenv:Body>' + 
	'</soapenv:Envelope>';

var ctx =  { request: message 
           , url: "https://www.aercloud.net/webapi?wsdl"
           , action: "http://tempuri.org/IISMWebAPI/get_image_png"
           , contentType: "text/xml; chartset=utf16" 
           , contentEncoding: "text/xml"
           };

//add attachment to the soap request
ws.addAttachment(ctx, "request","//*[local-name(.)='get_image_pngResult']","me.png",'image/png');

var handlers =  [new Http()];

ws.send(handlers, ctx, function(ctx) {      
    //  //read an attachment from the soap response
    	console.log(ctx);
      var file = ws.getAttachment(ctx, "response", "//*[local-name(.)='get_image_pngResult']")
      //fs.writeFileSync("result.png", file)      
})

**Comment by yaronn** [comment]
I'm confused - I though you build a client but I see server code here also in addition to client. Does the client code calls your server code or another server code? the server code here does not return valid soap attachments so the ws client will not work with it.

if you access an external web service then your handlers must contain Mtom:

                   var handlers =  [ new Mtom()
                    , new Http()
                    ];

**Comment by minyixie** [comment]
Sorry, my code may confuse you but you are right. This code is the server
to a client page, and in this server，we have a request to another server
for an imag.

Yes, I will use the Mtom in, and tried the getattachment() only but the
reaults are not available.

**Comment by yaronn** [comment]
can you build a small code snippet that only tries to call the iisnode
service and get the attachment? (no server code so it is simple)
after you do this - please publish the code and the result you get. after
you publish the code, can I run it also, or is the service secured?

On Thu, Mar 26, 2015 at 12:55 PM, minyixie <notifications@github.com> wrote:

> Sorry, my code may confuse you but you are right. This code is the server
> to a client page, and in this server，we have a request to another server
> for an imag.
>
> Yes, I will use the Mtom in, and tried the getattachment() only but the
> reaults are not available.
> On 26/03/2015 9:18 PM, "Yaron Naveh" <notifications@github.com> wrote:
>
> > I'm confused - I though you build a client but I see server code here
> also
> > in addition to client. Does the client code calls your server code or
> > another server code? the server code here does not return valid soap
> > attachments so the ws client will not work with it.
> >
> > if you access an external web service then your handlers must contain
> Mtom:
> >
> > var handlers = [ new Mtom()
> > , new Http()
> > ];
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/yaronn/ws.js/issues/11#issuecomment-86438916>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/ws.js/issues/11#issuecomment-86451812>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by minyixie** [comment]
I delete the non-relavent code, and only leave those for getting the image. Please feel free to use the following code for testing and don't change the access key value.

By using the following code, the same issues exist. 

var http = require("http");
var url = require("url");

var ws = require('ws.js'),
	Http = ws.Http,
	Mtom = ws.Mtom;

var message = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">' +
	   '<soapenv:Header/>' + 
	   '<soapenv:Body>' + 
		  '<tem:get_image_png>' + 
			 '' + 
			 '<tem:access_key>UxKjqyuQUANqAC8eNVG6EOjs2FBHZ6N41239</tem:access_key>' + 
			 '' + 
			 '<tem:name>girl</tem:name>' + 
			 '' + 
			 '<tem:image_name>girl1</tem:image_name>' +
		  '</tem:get_image_png>' + 
	   '</soapenv:Body>' + 
	'</soapenv:Envelope>';

var ctx =  { request: message 
           , url: "https://www.aercloud.net/webapi?wsdl"
           , action: "http://tempuri.org/IISMWebAPI/get_image_png"
           , contentType: "text/xml; chartset=utf16" 
           , contentEncoding: "text/xml"
           };

//add attachment to the soap request
//ws.addAttachment(ctx, "request","//*[local-name(.)='get_image_pngResult']","me.png",'image/png');

var handlers =  [new Http(), new Mtom()];

ws.send(handlers, ctx, function(ctx) {      
    //read an attachment from the soap response
    	console.log(ctx);
    //var file = ws.getAttachment(ctx, "response", "//*[local-name(.)='get_image_pngResult']")
    //fs.writeFileSync("result.png", file)      
})

**Comment by yaronn** [comment]
when I call this code now the response does not contain any png (it contains two mime parts but the second one is empty). can you check this?

also the order of handlers should be different (first mtom than http).

**Comment by minyixie** [comment]
Sorry, it should be some staff delete the image library so you could get nothing. I add a image to the library. 

But, with the about code, if I use the order

handler = {new Http(), new Mtom}

the image data is there. 

If i change the order

handler = {new Mtom(), new Http()}

the image data is gone.

**Comment by yaronn** [comment]
hi

this looks like an issue with the xpath engine.
this is the response:

    <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body>       
    <get_image_pngResponse xmlns="http://tempuri.org/"><get_image_pngResult><xop:Include   
    href="cid:http://tempuri.org/1/635629682617340181" 
    xmlns:xop="http://www.w3.org/2004/08/xop/include"/></get_image_pngResult>
    </get_image_pngResponse></s:Body></s:Envelope>

the href is:

    cid:http://tempuri.org/1/635629682617340181

the xpath is built using the method encodeURIComponent so it is:

    //*[@href='cid:http%3A%2F%2Ftempuri.org%2F1%2F635629682617340181']//parent::*

but the xpath engine does not know to match the escaped characters (%2F --> /)
the library has been tested on xml's where the response used the escaped characters as well so this was not an issue. I am not sure if the current response is valid or not, but it should be supported either way.

**a quick workaround:**

use the new handlers order (mtom first, than http).
also add this in the beginning of your application:

    encodeURIComponent = function(s) {return s}

(it will override the encodeURIComponent global method - it will not work if you need it in other places. you could replace it just before you call the ws and return it back after if you want).

so the full code will be:

    var http = require("http");
    var url = require("url");

    encodeURIComponent = function(s) {return s}

    var ws = require('ws.js'),
       Http = ws.Http,
       Mtom = ws.Mtom;

    var message = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"     
    xmlns:tem="http://tempuri.org/">' +
          '<soapenv:Header/>' + 
          '<soapenv:Body>' + 
            '<tem:get_image_png>' + 
              '' + 
              '<tem:access_key>UxKjqyuQUANqAC8eNVG6EOjs2FBHZ6N41239</tem:access_key>' + 
              '' + 
              '<tem:name>girl</tem:name>' + 
              '' + 
              '<tem:image_name>girl1</tem:image_name>' +
            '</tem:get_image_png>' + 
          '</soapenv:Body>' + 
       '</soapenv:Envelope>';

    var ctx =  { request: message 
               , url: "https://www.aercloud.net/webapi?wsdl"
               , action: "http://tempuri.org/IISMWebAPI/get_image_png"
               , contentType: "text/xml; chartset=utf16" 
               , contentEncoding: "text/xml"
               };

    //add attachment to the soap request
    //ws.addAttachment(ctx, "request","//*[local-name(.)='get_image_pngResult']","me.png",'image/png');

    var handlers =  [new Mtom(), new Http()];

    ws.send(handlers, ctx, function(ctx) {      
        //read an attachment from the soap response
          //console.log(ctx);
          //console.log("done")
          var file = ws.getAttachment(ctx, "response", "//*[local-name(.)='get_image_pngResult']")
          require('fs').writeFileSync("result.png", file)      
          //console.log(file)
    })

**Comment by minyixie** [comment]
Hi Yaronn,

It is so appreciate  for your help and explanation, I will try your code
and feedback what will happen.

Regards
Minyi

**Comment by minyixie** [comment]
That is excellent and the image data is retrieved. 

Thank you so much.

**Comment by yaronn** [comment]
very happy to hear that!

**Comment by minyixie** [comment]
Hi Yaronn,

First thanks for your help. Then, could I know how and why you can get on
the right track to solve the problem?

By the way, do you have any recommended books that I could learn more on
JavaScript for node.js, or soap communication, or anything relavent to this
field? Hope that would not trouble you.

Best regards
Minyi

**Comment by yaronn** [comment]
Hi Minyi

I just debugged the code until I saw it reached a code path which it shouldn't (it could not find the attachment in the soap due to bad xpath). A more final solution would be to fix the xpath library.

I don't have specific books to recommend. I like to look at how open source projects are written and also write some myself - this is the best way to learn imo. But you could google some good tutorials for both.

Yaron

**Comment by minyixie** [comment]
Thanks Yaronn for your help and suggests.

Regards
Minyi

**Comment by chrisgh1** [comment]
First off let me say thank you to @yaronn and @minyixie for this post that ultimately got me to a working situation in my related issue https://github.com/yaronn/ws.js/issues/35

I have just one question:
@yaronn you said for using the workaround `encodeURIComponent = function(s) {return s}`
> (it will override the encodeURIComponent global method - it will not work if you need it in other places. you could replace it just before you call the ws and return it back after if you want).

could you expand on this statement and also how would you demonstrate how you would return it back after?

**Comment by chrisgh1** [comment]
So I'm doing this to revert the override of the encodeURIComponent global method

`var _encodeURIComponent = encodeURIComponent; 
encodeURIComponent = function(s) {return s}
encodeURIComponent = _encodeURIComponent; 
`
Is there a better way of doing this?
