### ISSUE TITLE
Support for http basic auth

### ISSUE THREAD

**Issue by maccyber** [yaronn/ws.js#13]
Can you please add support for http basic auth?

I got it to work with adding the following ugly-hack to ws.js/lib/handlers/client/http.js

```javascript
...
HttpClientHandler.prototype.send = function(ctx, callback) {

var username = 'username';
var password = 'password';
var auth = 'Basic ' + new Buffer(username + ':' + password).toString('base64');

request.post({ url: ctx.url
               , body: ctx.request
               , headers: { "Authorization": auth
                          , "SOAPAction": ctx.action
...

**Comment by yaronn** [comment]
ok, I'll try to do it when I have time.

meanwhile you might get away with adding it to the url instead of the patch:

    http://username:password@some.server.com

or to make the patch less ugly you could add configuration to the request method to do it:

    request.post(... , auth: {user: 'u', pass: 'p'})

(if you add these settings globally you could do it without a patch)

**Comment by maccyber** [comment]
Thanks @yaronn 
```
http://username:password@some.server.com
```

worked just fine!
